### ISSUE TITLE
State history and time-travel

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#1]
Do you somehow keep track of the state history, or are there plans for that?
One of the cool Redux features is the possibility to - via browser plugn - monitor the state changes and to time travel between them...

**Comment by ciscoheat** [comment]
This will definitely be a middleware feature, either as a built-in or you could easily create your own with it. Stay tuned!

**Comment by cambiata** [comment]
Cool! I tend to extend the use of React towards an "event driven" solution as a whole, not only strictly for data state changes. For example, I fire actions for intializing firebase, checking user-login status etc...
Just sayin'.

**Comment by ciscoheat** [comment]
Middleware is in place now, check the docs.
