### ISSUE TITLE
Haxe 4 preview 5 runtime error when targeting js

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#10]
There seems to be a runtime problem with when targeting js using Haxe 4 preview 5, released the other day. (--interp works fine!)

At runtime, I get the following:
```
d:\Dropbox\_dev\fb-stack\dev\_setup-deepstate\public\test.js:292
var ds_Subscription = $hxEnums["ds.Subscription"] = { __ename__ : true, __constructs__ : ["Partial","Full"]
                      ^

ReferenceError: $hxEnums is not defined
    at d:\Dropbox\_dev\fb-stack\dev\_setup-deepstate\public\test.js:292:23
    at Object.<anonymous> (d:\Dropbox\_dev\fb-stack\dev\_setup-deepstate\public\test.js:317:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
Error: Command failed with error 1
The terminal process terminated with exit code: 1
```

**Comment by ciscoheat** [comment]
It works fine for me for Node, what environment and test code are you using?

**Comment by cambiata** [comment]
Seems related to https://github.com/HaxeFoundation/haxe/issues/7552

**Comment by cambiata** [comment]
Hello again!

Deepstate now seems to run fine with nightly build Haxe 4 preview 5 (I'm using 4.0.0-preview.5+80f42bdc3). 👍 I guess that it's fixed by this reversion: https://github.com/HaxeFoundation/haxe/issues/7552#issuecomment-443424275

However, there are some confusing vscode code completion messages cropping up: 
![code-completion-error](https://user-images.githubusercontent.com/217074/50769003-d62f8e00-1282-11e9-9c7f-3e4adabeabc6.png)

**Comment by ciscoheat** [comment]
Hey hey, I can't seem to reproduce these. Anything special about the project?

**Comment by cambiata** [comment]
Nothing other than the Haxe 4 preview 5 nightly version...
Will try on my other machine...

**Comment by cambiata** [comment]
Hello again! Same problem on my other machine!
Please note that I'm on preview 5 **nightly build** (because of the $hxEnums error in preview 5).
Haxe Compiler 4.0.0-preview.5+a37320cb5

**Comment by ciscoheat** [comment]
Strange, I haven't been able to reproduce it on any preview or project, the latest I tried was 2019-01-17. But the autocompletion fails for macro arguments in preview 5, so in any case, for the best experience currently I'd go back to preview 4.

**Comment by ciscoheat** [comment]
It happened to me by chance, so I hope it's fixed now. If not, let me know what methods are still producing the error.

**Comment by cambiata** [comment]
No problem nowadays.
