### ISSUE TITLE
Problem with DataClass default values

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#12]
A DC class that is defined using a default value, for example
```
class Example implements DataClass {
	public final id:String = 'defaultBookId';
}
```
causes the following compile time error:
`Unsupported DeepState type for book.title: TLazy(haxe.macro.LazyType)`

**Comment by cambiata** [comment]
Ah, quickly fixed! :-)

**Comment by cambiata** [comment]
Updated to latest git version, still seem to be the same problem...

**Comment by ciscoheat** [comment]
Can I see the class you're trying to instantiate?

**Comment by cambiata** [comment]
Here's a minimal non-working example causing the following compiletime error:
`src/Main.hx:12: character 1 : Unsupported DeepState type for test.id: TLazy(haxe.macro.LazyType)`

```
class Main {
	static function main() {		
		var s = new Store();
	}
}

typedef State = {
	final test:Test;
}

class Store extends DeepState<State> {
	public function new() {
		super({test: new Test({id: 'abc'})});
	}
}

class Test implements DataClass {
	public final id:String = 'id'; // works fine without default parameter
}

```

**Comment by cambiata** [comment]
Sorry - when using the current git-version of deepstate, it works fine! Thanx!
