### ISSUE TITLE
DataClass field with anonymous object data?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#13]
I'm not able to define a DC class with anonymous object data.
Neither of these seem to work: 

```
class Example implements DataClass {
	public final data1:ds.ImmutableJson;
	public final data2:haxe.DynamicAccess<Dynamic>;
}
```

The first one causes
`Unsupported DataClass type: TDynamic`

The second one causes
`/dataclass/macros/Builder.hx:116: characters 43-44 : Uncaught exception field access on null`

Maybe I'm missing something..?

**Comment by ciscoheat** [comment]
Should be fixed now by https://github.com/ciscoheat/dataclass/commit/6961379d181f51dc544ad707967cd831c5592224

**Comment by ciscoheat** [comment]
(Haxelib updated)
