### ISSUE TITLE
Problem with chainable/tree-able DataClass objects

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#14]
DeepState doesn't seem to like DataClass objects with fields of it's own type:

```
class Test implements DataClass {
	public final test:Test = null; // <- 
}
```
This causes the compiler to stall.
No big deal for me now, but could cause problem when implementing tree-like structures, lists etc.

**Comment by ciscoheat** [comment]
Thank you, will fix!

**Comment by ciscoheat** [comment]
Fixed now.
