### ISSUE TITLE
Immediate evaluation of subscription listener when attached to the state asset?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#15]
Would it be possible (as an option?) to let a subscription listener be run/evaluated when attached to the asset object? If so, that could reduce some boilerplate in the view classes.

As an example, here's a simplified view as it looks right now:
```
class ChapterView extends DomComponent {
	var store:AppStore = null;
	var user:UserData = null;
	var chapter:Chapter = null;

	public function new(el:js.html.Element, store:AppStore) {
		this.store = store;

                // 1. Field data is initially set here...
		this.chapter = this.store.state.chapter;
		this.user = this.store.state.userState.user;

		super(el);

		this.store.subscribeTo(this.store.state.chapter,
			this.store.state.userState.user,
			(chapter, user) -> {
                		// 2. ...and later, upon further state changes, here:
				this.chapter = chapter;
				this.user = user;
				this.render();
			});
	}

	// View method, à la Mithril
	override public function view():OneOf3<String, js.html.Element, Array<js.html.Element>> {
      	        if (this.chapter.access > this.user.access) return m2('div', 'Forbidden access');
        
        	return [
	            m2('h1', this.chapter.title),
	            m2('p', this.chapter.text),
	        ];
	}
}
```
What "bothers me" is that I have to pluck the state data twice, once initially (// 1.) and once in the subscription listener (//2.) Smells a bit like unnecessary code duplication.

Maybe the subscribe method could have an extra "immediateEvaluation" Bool parameter? If so, the view constructor could look like this:

	public function new(el:js.html.Element, store:AppStore) {
		this.store = store;

		super(el);

		this.store.subscribeTo(this.store.state.chapter,
			this.store.state.userState.user,
			(chapter, user)
			-> {
				this.chapter = chapter;
				this.user = user;
				this.render();
			}, true); // <- immediateEvaluation set to true
	}

Just an idea, to save a few lines of code... What you think?

**Comment by ciscoheat** [comment]
This has been added now.
