### ISSUE TITLE
array observal question

### ISSUE THREAD

**Issue by francescoagati** [ciscoheat/deepstate#18]
hi,
i have a litte question. can be possible observe an aray?
for example 
```
var player_id = 2;
var subscriber = observable.subscribe(    
    asset.state.players[player_id].name,
    name -> trace('Player changed name to ${p.firstName} ${p.name}')
);```

**Comment by ciscoheat** [comment]
Hi, observing with an array index isn't possible since it may not be of that length when the observation is made. I think the easiest way at the moment is to observe the whole state and check if the array changed there:

```haxe
var subscriber = observable.subscribe((prev, current) -> {
    if(prev.state.players != current.state.players) {
        // Check if some name changed
    }
});
```

**Comment by francescoagati** [comment]
understand thanks. but is possible trigger the change only for the array of players
something like 

```
var subscriber = observable.subscribe(    
    asset.state.players,
    players -> trace('Player changed name to ${players[2].name}')
);```

**Comment by ciscoheat** [comment]
Yes that works, though you have to check for yourself if `players[2].name` actually changed. It will trigger for any change in the array.

**Comment by francescoagati** [comment]
really thanks in this mode is good for me
