### ISSUE TITLE
Post-state-change observer hook?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#3]
Is there some kind of post-state-change hook where you could wrap something like a `mithril.M.redraw()` command?

**Comment by ciscoheat** [comment]
Not at the moment, there will probably be some event dispatcher later, even though I don't like hypergalactic GOTOs. :) The workaround right now is to override `DeepState.update` and call it from there:

```haxe
override public function update(action : DeepState.Action) {
    var newState = super.update(action);
    mithril.M.redraw();
    return newState;
}
```

**Comment by cambiata** [comment]
Fair enough! :-) Thanks!

**Comment by ciscoheat** [comment]
A simple observer/listener mechanism has been added now, check it out in the docs! Feedback appreciated.
