### ISSUE TITLE
Memoizable selectors?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#4]
Something like Reselect for computation of derived data, and memoizing it, would be really useful.

**Comment by ciscoheat** [comment]
That seems to be related to performance issues, doesn't it? In that case I'd like to wait until the API stabilizes and there are obvious problems with performance.

**Comment by cambiata** [comment]
Well, anyhow, it's not really something tied to the statemanager itself - rather a subject and library of its own.

In my case, I see the following advantages in using selectors:
- DRY. Computation of often-used derived data is centralized and close to the source instead of performed in the view.
- Performance. Not having to recalculate heavy views (markdown article with five embedded music score examples...) except for when it's actually needed.
- Dealing with Vanilla JS in a Virtual DOM context: (This is a special case, indeed!) As I'm partly using canvas drawing - wich isn't that easy combined with Virtual DOM solutions - I can trig Vanilla JS dom updates from the memoized functions, and rely on that they are fired only when the relevant state data is actually changed.

**Comment by cambiata** [comment]
From my p o w, the possibility to subscribe to changes in part(s) of the state ( #5) solves the same problems as selectors do. Thanks!

**Comment by ciscoheat** [comment]
Great, closing this for now then!
